name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Publish to NPM
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            corepack npm publish --tag next
          else
            corepack npm publish
          fi
